### ISSUE TITLE
RedisException: OOM command not allowed when used memory > 'maxmemory'

### ISSUE THREAD

**Issue by ianmjones** [deliciousbrains/spinupwp-plugin#40]
Since upgrading the SpinupWP plugin on a site, I'm seeing a constant stream of the following...

```
[20-Aug-2020 11:50:47 UTC] RedisException: OOM command not allowed when used memory > 'maxmemory'. in /sites/weglot.breakonexception.com/files/wp-content/object-cache.php:964
Stack trace:
#0 /sites/weglot.breakonexception.com/files/wp-content/object-cache.php(964): Redis->set('weglot.breakone...', 'a:135:{s:7:"sit...', Array)
#1 /sites/weglot.breakonexception.com/files/wp-content/object-cache.php(893): WP_Object_Cache->add_or_replace(true, 'alloptions', Array, 'options', 0)
#2 /sites/weglot.breakonexception.com/files/wp-content/object-cache.php(34): WP_Object_Cache->add('alloptions', Array, 'options', 0)
#3 /sites/weglot.breakonexception.com/files/wp-includes/option.php(231): wp_cache_add('alloptions', Array, 'options')
#4 /sites/weglot.breakonexception.com/files/wp-includes/functions.php(1706): wp_load_alloptions()
#5 /sites/weglot.breakonexception.com/files/wp-includes/load.php(606): is_blog_installed()
#6 /sites/weglot.breakonexception.com/files/wp-settings.php(161): wp_not_installed()
#7 /sites/weglot.breakonexception.com/files/wp-config.php(86): require_once('/sites/weglot.b...')
#8 /sites/weglot.breakonexception.com/files/wp-load.php(37): require_once('/sites/weglot.b...')
#9 /sites/weglot.breakonexception.com/files/wp-admin/admin-ajax.php(22): require_once('/sites/weglot.b...')
#10 {main}
```

**Comment by ianmjones** [comment]
Here's OME's diagnostics from the same site in case it helps...

```
site_url(): https://weglot.breakonexception.com
home_url(): https://weglot.breakonexception.com
Database Name: weglot
Table Prefix: aqh_
WordPress: 5.4.2
Web Server: nginx/1.15.8
PHP: 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 4 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 64 MB
PHP Time Limit: 30
PHP Error Log: /sites/weglot.breakonexception.com/logs/debug.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1c  28 May 2019
cURL: 7.58.0
Zlib Compression: Enabled
PHP GD: 2.2.5
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 5
Offloaded Media Files: 5
Not Offloaded Media Files: 0

Number of Image Sizes: 7

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
post-thumbnail (none)

WP_CONTENT_DIR: /sites/weglot.breakonexception.com/files/wp-content
WP_CONTENT_URL: https://weglot.breakonexception.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /sites/weglot.breakonexception.com/files/wp-content/plugins
WP_PLUGIN_URL: https://weglot.breakonexception.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://weglot.breakonexception.com/wp‑content/uploads/2020/08/photo.jpg
Offload URL:
https://paris.breakonexception.com/wp‑content/uploads/2020/08/20115630/photo.jpg

OME Metadata Version: 8

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: ianmjones-wpom-weglot-paris
Region: eu-west-3
Block All Public Access: Disabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Delivery Provider: Other
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): paris.breakonexception.com

Force HTTPS: Off

Remove Files From Server: Off

Posts Count: 18

Pro Upgrade: 
License Status: Valid
License Constant: Off

Host IP: 104.248.172.97
Background Jobs: 

Assets Pull Addon:
Rewrite URLs: On
Domain: paris.breakonexception.com
Force HTTPS: Off
Domain Check: OK

Active Theme Name: Twenty Fifteen
Active Theme Version: 2.7
Active Theme Folder: twentyfifteen

Active Plugins:
Limit Login Attempts Reloaded (v2.15.1) by WPChef
SpinupWP (v1.2) by Delicious Brains
WP Offload Media (v2.4.1) by Delicious Brains
WP Offload Media - Assets Pull Addon (v1.1.1) by Delicious Brains
WP Offload SES (v1.5.3) by Delicious Brains
WP Table Pixie (v1.1.2) by Byte Pixie
Weglot Translate (v3.1.9) by Weglot Translate team

Must-use Plugins:
SpinupWP Debug Log Path (v1.0) by Delicious Brains


Drop-ins:
object-cache.php - SpinupWP Redis Object Cache Drop-In
```

**Comment by A5hleyRich** [comment]
@ianmjones this isn't a plugin issue. If `maxmemory` is configured in your Redis config, you need to set an evict policy. 

https://docs.redislabs.com/latest/rs/administering/database-operations/eviction-policy/
